Algoritmo "Prêmio"

var
   vet1 : vetor [0..2] de inteiro
   contador : inteiro


Inicio
   para contador de 0 ate 2 faca
      escreva("Digite o seu total de vendas: ")
      leia (vet1[contador])
      vet1[0] <- 10
      vet1[1] <- 15
      vet1[2] <- 20
      se vet1[contador] >= vet1[contador] entao
         escreval ("Você ganhou!!")
      senao
         escreval ("Não ganhou")
      fimse
      escreval("--------------------------------")
   fimpara





Fimalgoritmo