Algoritmo "três"

Var
resposta : caractere
nome1 , nome2 : caractere
altura1 , altura2 : real




Inicio
escreva ("Digite o primeiro nome: ")
leia  (nome1)
escreva ("Digite a sua altura: ")
leia (altura1)
escreva ("Digite o segundo nome: ")
leia (nome2)
escreva ("Digite a sua altura: ")
leia (altura2)

se (altura1 > altura2) entao
escreva (nome1, " é mais alto(a) que ", nome2)
senao
se (altura2 > altura1) entao
escreva (nome2, " é mais alto(a) que ", nome1)
fimse
fimse


fimalgoritmo