Algoritmo "vetor3"
var

v1:vetor[1..2]de inteiro

v2:vetor[1..2]de inteiro

v3:vetor[1..4]de inteiro

inicio

Escreva("Informe um valor: ")

leia(v1[1])

Escreva("Informe um valor: ")

leia(v1[2])

escreva ("Informe um valor: ")
leia(v2[1])
escreva ("Informe um valor: ")
leia (v2[2])

v3[1] <- v1[1]
v3[2] <- v1[2]
v3[3] <- v2[1]
v3[4] <- v2[2]

Escreva("Os valores dos vetores é : ",v3[1], v3[2] , v3[3], v3[4])

Fimalgoritmo